mariadb:
  configmap:
    name: config-mariadb-service-1-iobdbdqo4e
  secret:
    name: secret-mariadb-service-1-iobdbdqo4e
    username: test
    password: "Root1234!"
    root_password: "Root1234!"
    database: tet
    dbhost: mariadb-service-1-iobdbdqo4e
    port: 3306
  statefulset:
    name: mariadb-service-1-iobdbdqo4e
    image:
      url: registry.turacocloud.com/turaco-common/mariadb:10.4.11
service:
  port:
    name: http
    l4_protocol: TCP
    port: 3306
    targetPort: 3306
  label: mariadb-service-1-iobdbdqo4e
  name: mariadb-service-1-iobdbdqo4e
  selector: mariadb-service-1-iobdbdqo4e
  type:
  - ClusterIP
  - NodePort
statefulset:
  name: mariadb-service-1-iobdbdqo4e
  spec:
    name: mariadb-service-1-iobdbdqo4e
    servicename: mariadb-service-1-iobdbdqo4e
  replicas: 1
  container:
    name: mariadb-service-1-iobdbdqo4e
    port: 3306
  volume:
    name: pvc-mariadb-service-1-iobdbdqo4e
  resource:
    request:
      memory: 250Mi
      cpu: 0.25
    limits:
      memory: 0Mi
      cpu: 0
  hpa:
    name: hpa-mariadb-service-1-iobdbdqo4e
    minReplicas: 1
    maxReplicas: 1
    cpu: 70
    memory: -@memAutoScale@-
namespace: testdb-dev
secret:
  name: 
  registry:
    name: regsecret
    url: turaco-dev-registry.turacocloud.com/dev-turaco-workspace-268/turaco
    username: robot$turaco_common
    password: Zv7beYWhgCQSOUoxZQK1RGWHdvAMltXx
    email: info@twolinecode.com
pvc:
  name: pvc-mariadb-service-1-iobdbdqo4e
  storageClass: tlc-block-sc
  size: 5Gi
  accessMode: ReadWriteOnce
